steps:
  - id: "Run Tests"
    name: maven:3.9.4-eclipse-temurin-20
    entrypoint: mvn
    args: ["clean", "test"]

  - id: "Build Docker Image"
    name: gcr.io/cloud-builders/docker
    args: [
      "build",
      "-t", "europe-west6-docker.pkg.dev/booknow-akin/docker-repo-booknow/booknow-docker-img:$COMMIT_SHA",
      "." ]

  - id: "Push Docker Image"
    name: gcr.io/cloud-builders/docker
    args: [ "push", "europe-west6-docker.pkg.dev/booknow-akin/docker-repo-booknow/booknow-docker-img:$COMMIT_SHA" ]

  - id: "Deploy to Cloud Run"
    name: "gcr.io/cloud-builders/gcloud"
    args: [
      "run",
      "deploy",
      "booknow",
      "--min-instances",
      "0",
      "--max-instances",
      "1",
      "--image",
      "europe-west6-docker.pkg.dev/booknow-akin/docker-repo-booknow/booknow-docker-img:$COMMIT_SHA",
      "--region",
      "europe-west6",
      "--allow-unauthenticated",
      "--port",
      "8080"
    ]

options:
   logging: CLOUD_LOGGING_ONLY


