steps:
  - id: "Run Tests"
    name: maven:3.9.4-eclipse-temurin-20
    entrypoint: mvn
    args: ["clean", "test"]

  - id: "Build Docker Image"
    name: gcr.io/cloud-builders/docker
    args: [
      "build",
      "-f", "src/Dockerfile",
      "-t", "europe-west6-docker.pkg.dev/booknow-akin/docker-repo-booknow/booknow-docker-img:$COMMIT_SHA",
      ".." ] # Build-Kontext ist jetzt das übergeordnete Verzeichnis

  - id: "Push Docker Image"
    name: gcr.io/cloud-builders/docker
    args: [ "push", "europe-west6-docker.pkg.dev/booknow-akin/docker-repo-booknow/booknow-docker-img:$COMMIT_SHA" ]


options:
   logging: CLOUD_LOGGING_ONLY


