steps:
  - id: "Run Tests"
    name: maven:3.9.4-eclipse-temurin-20
    entrypoint: mvn
    args: ["test"]

  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']

  - name: 'alpine:latest'
    entrypoint: sh
    args:
      - '-c'
      - |
        echo "Warten auf PostgreSQL..."
        until nc -z localhost 5432; do
          sleep 1
        done
        echo "PostgreSQL ist bereit!"

options:
   logging: CLOUD_LOGGING_ONLY
  #- id: "Build Application"
  #  name: maven:3.9.4-eclipse-temurin-20
  #  entrypoint: mvn
  #  args: ["clean", "package", "-DskipTests"]
  #  waitFor: ["Run Tests"]
