steps:
  - id: "Run Tests"
    name: maven:3.9.4-eclipse-temurin-20
    entrypoint: mvn
    args: ["test"]

  - id: "Build Application"
    name: maven:3.9.4-eclipse-temurin-20
    entrypoint: mvn
    args: ["clean", "package", "-DskipTests"]
    waitFor: ["Run Tests"]

    options:
      logging: CLOUD_LOGGING_ONLY